eureka :
  instance :
    prefer-ip-address : true
  client :
    fetch-registry : true
    registry-with-eureka : true
    service-url :
      defaultZone : http://localhost:8114/eureka

management :
  health:
    circuitbreakers:
      enabled : true
  endpoints:
    web:
      exposure:
        include : true

  endpoint :
    health:
      show-details : always
